## Install Prometheus Operator CRDs
crds:
  enabled: true 

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d
    retentionSize: "8GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi