replicaCount: 3

resources: 
 requests:
   cpu: 500m
   memory: 512Mi
 limits:
   cpu: 1000m
   memory: 1024Mi

additionalEnv:
  - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "off"
  - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD
    value: "on"
  - name: DOCKER_VERNEMQ_VMQ_PASSWD__PASSWORD_FILE
    value: "/etc/vernemq/passwords"

envFrom:
  - secretRef:
      name: vernemq-users

service:  
  enabled: true
  type: ClusterIP
  mqtt:
    enabled: true
    port: 1883
    nodePort: 1883
  mqtts:
    enabled: false
    port: 8883
    nodePort: 8883
  ws:
    enabled: true
    port: 8080
    nodePort: 8080
  wss:
    enabled: false
    port: 8443
    nodePort: 8443
  api:
    enabled: false
    type: ClusterIP
    port: 8888
    nodePort: 38888
    annotations: {}