resources:
  - namespace.yaml
  - virtualservice.yaml

helmCharts:
  - name: kiali-operator
    repo: https://kiali.org/helm-charts
    version: 1.88.0
    releaseName: kiali-operator
    namespace: kiali-operator
    includeCRDs: true
    valuesFile: values.yaml