resources:
  - namespace.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.15.0
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesInline:
      crds:
        enabled: true
