resources:
  - namespaces.yaml
  - gateway-ingress.yaml
  - gateway-egress.yaml

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.22.1
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true

  - name: cni
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.22.1
    releaseName: istio-cni
    namespace: istio-system
    valuesInline:
      profile: ambient

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.22.1
    releaseName: istio-cni
    namespace: istio-system
    valuesInline:
      profile: ambient

  - name: ztunnel
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.22.1
    releaseName: ztunnel
    namespace: istio-system

  # ao instalar o gateway ao mesmo tempo que os pods é necessário apagar o pods para que o mesmo seja recriado corretamente
  # https://github.com/istio/istio/issues/35789
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.22.1
    releaseName: istio-ingress
    namespace: istio-ingress

  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.22.1
    releaseName: istio-egress
    namespace: istio-egress
    valuesInline:
      service:
        type: ClusterIP  # Egress gateways não necessitam de IP de LoadBalancer externo