namespace: plantsuite

labels:
  - pairs:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: plantsuite
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: 1.0.1-beta.28
    includeTemplates: true

images:
  - name: plantsuite.azurecr.io/plantsuite-gateway
    newTag: 1.0.1-beta.28
  - name: plantsuite.azurecr.io/plantsuite-gateway-ui
    newTag: 1.0.1-beta.28

resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml

configMapGenerator:
  - name: gateway-appsettings
    files:
      - appsettings.json
